---
# Per environment values which override defaults in hmpps-domain-explorer-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: domain-explorer-ui-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://domain-explorer-ui-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    DOMAIN_EXPLORER_API_URL: "https://domain-explorer-api-dev.hmpps.service.justice.gov.uk"
    ENVIRONMENT_NAME: PRE-PRODUCTION
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: hmpps-people-on-probation-nonprod
