---
# Per environment values which override defaults in hmpps-domain-explorer-ui/values.yaml

generic-service:
  ingress:
    host: domain-explorer-ui.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://domain-explorer-ui.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    DOMAIN_EXPLORER_API_URL: 'https://hmpps-domain-explorer.hmpps.service.justice.gov.uk'
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: hmpps-people-on-probation-nonprod
